### PR TITLE
fix(nav): ensure bottom navigation icons are always clickable

### LINKED ISSUE #393: Fix Bottom Navigation Icons Sometimes Unclickable
**Description:**  
On some top-level screens (e.g., Events, Tickets), the bottom navigation icons are occasionally unresponsive after navigating to child screens. Other screens (e.g., Map, Profile) generally work as expected.

**Steps to Reproduce:**  
1. Open the app and sign in.  
2. Go to the Feed screen.  
3. Click on an event to open the Event Details screen.  
4. Click to view the Event on the Map.  
5. Attempt to tap the bottom navigation icon for the Feed screen.  

**Expected Behavior:**  
Tapping a bottom navigation icon for a top-level screen should always navigate to that screen.  

**Actual Behavior:**  
Icons on certain screens sometimes do not respond, preventing navigation via the bottom bar.

### PR DESCRIPTION
**Pull request by Zeleph25**
## Description
This PR fixes the issue where bottom navigation icons for top-level screens (Feed, Tickets, Map, Profile) were occasionally unresponsive after navigating to child screens like Event Details.

Now, tapping a bottom navigation icon always navigates correctly to the corresponding top-level screen, ensuring consistent behavior across the app.

## Changes
- Added `navigateToTopLevel` function to ensure bottom navigation always navigates to the correct top-level screen.
- Ensured that bottom navigation interactions do not get blocked by previous navigation state.

## Testing
1. Open the app and sign in.
2. Navigate to the Feed screen.
3. Click on an event to open Event Details.
4. Click to view the Event on the Map.
5. Tap the bottom navigation icon for Feed — now navigates correctly every time.
6. Repeat for Tickets, Map, and Profile screens to confirm consistent behavior.
7. Run all tests to ensure no regressions were introduced.

## Related Issue
Closes #393

### CODE REVIEW

File: app/src/main/java/ch/onepass/onepass/ui/navigation/AppNavHost.kt [hunk 1]
```diff
@@ -332,3 +332,17 @@ fun AppNavHost(
...
+ *
+ * @param route The route string of the top-level destination to navigate to.
+ */
+fun NavHostController.navigateToTopLevel(route: String) {
+  this.navigate(route) {
+    launchSingleTop = true
+    restoreState = false
+    popUpTo(route) { inclusive = true }
+  }
+}
```
Comment (RD418) [inline app/src/main/java/ch/onepass/onepass/ui/navigation/AppNavHost.kt]: Super fix ! Our code was creating multiples identitical screens in the navigation stack, It's much better to clear them with these options.
