### PR TITLE
feat: fix currency twice in market

### LINKED ISSUE #497: Fix Ticket Currency Shown Twice in Market UI
## Description

In the Market Ticket UI, the ticket price displays the currency **twice**, which creates a confusing and cluttered appearance.

1. **Expected Behavior**: The ticket price should display the **amount followed by the currency once** (e.g., "CHF 50").

2. **Actual Behavior**: The ticket price shows the currency **two times** (e.g., "CHF CHF 50"), making the UI look incorrect.

## Steps to Reproduce

1. Buy a ticket.  
2. Sell the ticket in the market.  
3. Open another account and view the ticket listed in the market.  
4. Notice that the currency is displayed twice.

## Proposed Fix

Update the UI to ensure the currency is displayed **only once** alongside the ticket price, maintaining a clean and user-friendly interface.

### PR DESCRIPTION
**Pull request by Zeleph25**
## Description
This PR fixes an issue where the ticket price in the Market Ticket UI was displaying the currency **twice**. After this fix, the ticket price shows the currency **only once**, improving clarity and maintaining a clean interface.

## Related Issues
Closes #497

## Preview

**Before:**  
Screenshot 2025-12-16 at 13 41 56

**After:**  
Screenshot 2025-12-16 at 13 41 19

## How to Test
1. Open the Market Ticket screen in the app and observe the ticket price.  
2. Buy a ticket.  
3. Sell the ticket in the market.  
4. Open another account and view the ticket listed in the market.  
5. Verify that the ticket price displays correctly with the currency **only once**.  
6. Ensure no other prices or currencies in the app are affected.

### CODE REVIEW

File: app/src/androidTest/java/ch/onepass/onepass/ui/myevents/MarketTicketCardTest.kt [hunk 1]
```diff
@@ -225,4 +227,25 @@ class MarketTicketCardTest {
...
+        .onNodeWithTag(MyEventsTestTags.MARKET_TICKET_SELLER_PRICE)
+        .assertIsDisplayed()
+        .assert(hasText("CHF 75"))
+
+    // Verify original price is displayed because it's different than the seller price
+    composeTestRule
+        .onNodeWithTag(MyEventsTestTags.MARKET_TICKET_ORIGINAL_PRICE, useUnmergedTree = true)
+        .assertIsDisplayed()
+        .assert(hasText("Original: CHF 100"))
+  }
```
Comment (RD418) [inline app/src/androidTest/java/ch/onepass/onepass/ui/myevents/MarketTicketCardTest.kt]: Well this test is odd, since it's the fix of the PR, but it increases line coverage.
