### PR TITLE
fix: authentification route in Nav & add tests

### LINKED ISSUE #202: Fix navigation start point to skip login when user is already authenticated
**Description:**
Currently, the app navigation always starts at the login page, even when the user is already logged in. This causes users to have to log in again every time they open the app.

**Expected behavior:**
When the app starts, it should check whether the user is already authenticated.

* If the user is logged in, navigate directly to the main screen (e.g., Events).
* If not, show the login page as usual.

**Steps to reproduce:**

1. Log in to the app.
2. Close the app completely.
3. Reopen the app.
4. Observe that it starts at the login page instead of the main screen.

**Proposed fix:**
Add a check at the app’s navigation entry point to determine whether the user session/token exists. Use that state to decide the initial route accordingly.

### PR DESCRIPTION
**Pull request by RD418**
### Summary
This PR fixes an authentication issue where reopening the app redirected users to the authentication screen.  
The issue was caused by hardcoded routes in `NavHost`.

### Changes
- Introduced a factory and dependency injection in `AppNavHost`.
- Updated the authentication `ViewModel` to handle state correctly.
- Added tests to ensure all screens share the same `AuthViewModel`.

### Testing
1. Pull this PR.
2. Run the app on your emulator. ⚠️
3. Verify that the authentication state persists correctly when reopening the app. ⚠️
4. Then review the code.

### Note
This PR structure and additional tests were created with AI assistance.
Closes #202

### CODE REVIEW

File: app/src/main/java/ch/onepass/onepass/ui/navigation/AppNavHost.kt [hunk 1]
```diff
@@ -33,106 +36,107 @@ fun AppNavHost(
...
+    }
 
-          val myEventsVm: MyEventsViewModel =
-              viewModel(
-                  factory = viewModelFactory { initializer { MyEventsViewModel(userId = uid) } })
-          MyEventsScreen(viewModel = myEventsVm, userQrData = "USER-QR-DEMO")
-        }
+    // ------------------ Tickets (My Events) ------------------
+    composable(Screen.Tickets.route) {
+      val uid = FirebaseAuth.getInstance().currentUser?.uid ?: "LOCAL_TEST_UID"
```
Comment (Zeleph25) [inline app/src/main/java/ch/onepass/onepass/ui/navigation/AppNavHost.kt]: The line 

```kotlin
val uid = FirebaseAuth.getInstance().currentUser?.uid ?: "LOCAL_TEST_UID"
```

is unsafe. Using a default UID like `"LOCAL_TEST_UID"` can lead to serious issues, such as multiple users sharing the same UID, which could result in actions like ticket purchases being incorrectly applied to all users.

Instead of providing a default value, the code should **fail safely** if `currentUser` is null—for example, by showing an error, preventing navigation to user-specific screens, or explicitly handling the null case.

File: app/src/main/java/ch/onepass/onepass/ui/navigation/AppNavHost.kt [hunk 2]
```diff
@@ -33,106 +36,107 @@ fun AppNavHost(
...
+      } else {
+        AuthScreen(
+            onSignedIn = {
+              navController.navigate(Screen.Events.route) {
+                popUpTo(Screen.Auth.route) { inclusive = true }
+                launchSingleTop = true
+              }
+            },
+            authViewModel = authViewModel)
+      }
```
[the remark this answers is not in the document]
Comment (RD418) [reply app/src/main/java/ch/onepass/onepass/ui/navigation/AppNavHost.kt]: This issue is not part of my changes, you are absolutely right, this sould be fixed in a another issue.

File: app/src/main/java/ch/onepass/onepass/ui/navigation/AppNavHost.kt (hunk 1 above)
Comment (RD418) [reply app/src/main/java/ch/onepass/onepass/ui/navigation/AppNavHost.kt]: Again this is not part of my code, but it can actually be fixed easily with the changes I made.
