### PR TITLE
feat(pass) : fix pass not generated for users on signup

### LINKED ISSUE #444: Fix: Pass not generated for users on signup
## Problem

Users don't receive a Pass on signup. QR validation fails because `pass` field is missing in Firestore.

**Current behavior:**
1. User signs up via Google Sign-In
2. User document created in Firestore without `pass` field
3. Scanner rejects QR code (missing signature)

**Root cause:** `onUserCreated` Cloud Function never executes.

## Expected after fix

Every new user gets a Pass with `uid`, `kid`, `signature`, `issuedAt`, and `active` fields. QR code works immediately in Profile screen and passes Scanner validation.

### PR DESCRIPTION
**Pull request by Hassan372**
## Description
Users can now see their QR code pass in the MyEvents screen. This pass gets scanned by event staff to validate tickets. The pass is automatically created when a user signs up (via Firebase Auth trigger) and loads smoothly with a loading indicator.

## Related Issues
Closes #444

## Changes

**UI (MyEvents screen)**
- Load and display user's QR code pass automatically when screen opens
- Show loading spinner while pass is being fetched or generated
- Handle errors gracefully if pass generation fails

**Backend (PassRepository)**
- Fix collection name bug: `"user"` → `"users"`
- Verify user is authenticated before generating pass
- Refresh auth token to ensure Cloud Function calls work properly
- Pass user ID explicitly to Cloud Function

**Cloud Functions**
- `generateUserPass`: Add proper error handling with try-catch and detailed logging
- `onUserCreated`: Generate pass automatically when user creates account (moved from Firestore trigger to Auth trigger)

### CODE REVIEW

File: app/src/main/java/ch/onepass/onepass/model/pass/PassRepositoryFirebase.kt [hunk 1]
```diff
@@ -47,15 +48,31 @@ class PassRepositoryFirebase(
...
     require(uid.isNotBlank()) { "uid required" }
 
-    // 1) If present in Firestore, return it
-    users.document(uid).get().await().toPass()?.let {
-      return@runCatching it
+    // 1) Verify that the user is authenticated
+    val currentUser =
+        FirebaseAuth.getInstance().currentUser
+            ?: throw IllegalStateException("User not authenticated")
+
```
Comment (RD418) [inline app/src/main/java/ch/onepass/onepass/model/pass/PassRepositoryFirebase.kt]: It's better to use DI for this cases, so that we make sure we have only one instance

File: app/src/main/java/ch/onepass/onepass/ui/myevents/QrCodeComponent.kt
Comment (RD418) [inline app/src/main/java/ch/onepass/onepass/ui/myevents/QrCodeComponent.kt]: Everything looks fine here.
